#!/bin/bash
# nanjing
# url="/var/www/html/cacti/rra/nj-jq-dx6851_traffic_in_242.rrd"
# shanghai
# url="/var/www/html/cacti/rra/sh-pbs-h6720_traffic_in_201.rrd"
# zaozhuang
# url="/var/www/html/cacti/rra/zaoz-gmhy-s6720_traffic_in_295.rrd"
# MaAnShan_CTC
url="/var/www/html/cacti/rra/mas_ysxc-dx-6855_traffic_in_302.rrd"
fff=`echo $url | awk '{print NF}'`
# 循环一个月
for((i=1;i<=31;i++))
do
# 起始的时间
criqi=`date +%s -d "2020-03-31 00:00:00"`
eriqi=`date +%s -d "2020-03-31 23:59:00"`
# 处理和计算时间
ccriqi=`echo "$criqi + 86400 * $i" | bc`
eeriqi=`echo "$eriqi + 86400 * $i" | bc`
dt=`date -d "1970-01-01 UTC $ccriqi seconds" +%F`
# 循环获取每天流量的最大值
for((x=1;x<=$fff;x++))
do
uu=`echo $url | awk -v a=${x} '{print $a}'`
/usr/local/bin/rrdtool fetch $uu MAX --start $ccriqi --end $eeriqi | sed -e '/^$/d' | grep -v "traffic_in" | awk '{printf "%f\n",$2}' | sed 's/\-nan/0.0000000000e+00/g' >> /tmp/test${x}
done

                          ff=`cat /tmp/test1 | wc -l`
                          for((n=1;n<=$ff;n++))
                          # 计算几个流量图的流量总和
                           do
                                for((y=1;y<=$fff;y++))
                                do
                                tt=`cat /tmp/test${y} | sed -n ${n}p`
                                echo $tt >> /tmp/fud
                                done
                                aa=`cat /tmp/fud | awk '{sum+=$0}END{print sum}'`
                                re=`echo "$aa" | awk '{sum=$0*8/1000000}END{printf "%.2f",sum}'`
                                echo $re >> /tmp/testz
                                rm -rf /tmp/fud
                          done
                                # 时间的输出
                                td=`cat /tmp/testz | sort -nr |  sed -n 1p`
                                if [ `echo "$td > 1000" | bc` -eq 1 ];then
                                # 流量的输出
                                tpt=`echo "scale=3;$td / 1000" | bc | awk '{printf "%.2f",$0}'`
                                # 按时间，流量的输出格式分2列放入csv
                                echo $dt,$tpt"G" 
                                echo "$dt,$tpt"G"" >> /root/Daily_traffic_peak.csv
                                else
                                echo $dt,$td"M" 
                                echo "$dt,$td"M"" >> /root/Daily_traffic_peak.csv
                                fi
 
for((b=1;b<=$fff;b++))
do
rm -rf /tmp/test${b}
done
rm -rf /tmp/testz
done;